local flightModes = {}
-- rover flight modes
flightModes[1]="Manual"
flightModes[2]="Acro"
flightModes[4]="Steering"
flightModes[5]="Hold"
flightModes[11]="Auto"
flightModes[12]="RTL"
flightModes[13]="SmartRTL"
flightModes[16]="Guided"
flightModes[17]="Initializing"
flightModes[0]=""
flightModes[6]=""
flightModes[7]=""
flightModes[8]=""
flightModes[9]=""
flightModes[10]=""
flightModes[14]=""
flightModes[15]=""
flightModes[18]=""
flightModes[19]=""
flightModes[20]=""
flightModes[21]=""
flightModes[22]=""
--
return {flightModes=flightModes}
